<div class="left-col">
    <button onclick="addRoot();"><?php echo $this->__('Add parent element'); ?></button>
    <button onclick="addChild();"><?php echo $this->__('Add child element'); ?></button>
    <div id="tree"></div>
</div>
<div class="right-col">
    <div class="fieldset-wide">
        <h2 id="header-1"><?php echo $this->__('Add parent element'); ?></h2>
        <h2 id="header-2"><?php echo $this->__('Add child element'); ?></h2>
        <h2 id="header-3"><?php echo $this->__('Edit element'); ?></h2>
            <form id="element-data" onsubmit="return false;">
                <table class="form-list">
                    <tr>
                        <td class="label">
                            <label>
                                <?php echo $this->__('Id'); ?>
                            </label>
                        </td>
                        <td class="value"><input type="text" id="id" readonly="readonly"/></td>
                    </tr>
                    <tr>
                        <td class="label">
                            <label for="name">
                                <?php echo $this->__('Name'); ?><span class="required">*</span>
                            </label>
                        </td>
                        <td class="value"><input class="input-text required-entry" type="text" id="name" name="name"/></td>
                    </tr>
                    <tr>
                        <td class="label"><?php echo $this->__('Parent element'); ?></td>
                        <td class="value">
                            <select id="parent" name="parent">
                                <option value="0" selected="selected"></option>
                            </select></td>
                    </tr>
                    <tr>
                        <td class="label"><?php echo $this->__('Link type'); ?></td>
                        <td class="value"><select id="type" name="type">
                            <option value="1"><?php echo $this->__('Catalog'); ?></option>
                            <option value="2"><?php echo $this->__('CMS page'); ?></option>
                            <option value="3"><?php echo $this->__('External page'); ?></option>
                        </select></td>
                    </tr>
                    <tr id="values">
                        <td class="label">
                            <label for="value">
                                <?php echo $this->__('Value'); ?><span class="required">*</span>
                            </label>
                        </td>
                        <td class="value">
                            <select id="catalog" name="value" class="validate-select">
                                <option value=""/>
                                <?php foreach ($this->getStoreCategories() as $_category){
                                    $_categories[$_category->getName()] = $_category;}
                                ksort($_categories);
                                ?>
                                <?php foreach ($_categories as $cat): ?>
                                    <?php if($cat->getName() && ($cat->getLevel() != 1)): ?>
                                        <option value="<?php echo($cat->getId()); ?>"><?php echo $cat->getName(); ?></option>
                                    <?php endif;?>
                                <?php endforeach; ?>
                            </select>
                            <select id="page" name="value" class="validate-select">
                                <option value=""/>
                                <?php foreach ($this->getCmsPages() as $page): ?>
                                    <?php if($page->getTitle()): ?>
                                        <option value="<?php echo($page->getId()); ?>"><?php echo $page->getTitle(); ?></option>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </select>
                            <input id="address" type="text" name="value" class="required-entry" />
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><?php echo $this->__('Priority'); ?></td>
                        <td class="value">
                            <input type="text" id="priority" name="priority">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <button id="add" onclick="saveElement()"><?php echo $this->__('Add'); ?></button>
                            <button id="delete" onclick="deleteElement()"><?php echo $this->__('Delete'); ?></button>
                        </td>
                    </tr>
                </table>
        </form>
    </div>
</div>

<script type="text/javascript">
    var form  = new varienForm('element-data');
    document.observe("dom:loaded", function () {
        $('delete').hide();
        $('id').up('tr').hide();
        $('priority').value = 1;
        getTree();
        selectMode(1);
        chooser(1);
    });
    Event.observe($("type"), 'change', function () {
        var type = $("type").value;
        chooser(type);
    });
    function selectMode(mode) {
        $$('h2').invoke('hide');
        $('header-' + mode).show();
    };
    function chooser(type) {
        $$("#values select,#values input").invoke('hide');
        if (type == 1) {
            $('catalog').show();
            $('catalog').addClassName('validate-select');
            $('address').removeClassName('required-entry');
            $('page').removeClassName('validate-select');
        }else if (type == 2) {
            $('page').show();
            $('page').addClassName('validate-select');
            $('address').removeClassName('required-entry');
            $('catalog').removeClassName('validate-select');
        }else if (type == 3) {
            $('address').show();
            $('address').addClassName('required-entry');
            $('page').removeClassName('validate-select');
            $('catalog').removeClassName('validate-select');
        }

        $$('#values td.value').each(function(element) {
            element.childElements().each(function(el) {
                if(el.hasClassName('validation-advice')) {
                    el.hide();
                }
            })
        });
    }
    function addRoot() {
        selectMode(1);
        $('id').value = '';
        $('id').up('tr').hide();
        $('name').value = '';
        $('parent').value = 0;
        $('priority').value = 1;
        $('add').innerHTML = Translator.translate('Add');
        $('delete').hide();
    }
    function addChild() {
        selectMode(2);
        $('id').value = '';
        $('id').up('tr').hide();
        $('name').value = '';
        $('priority').value = 1;
        $('add').innerHTML = Translator.translate('Add');
        if ($$("span.selected").size()) {
            var selected = $$("span.selected").first().id.split('-');
            $('parent').value = selected[1];
        }
        $('delete').hide();
    }
    function updateParentsList(response) {
        var select = $('parent');
        select.innerHTML = '';
        select.insert('<option value="0">' + " " + '</option>');
        response.data.each(function(el) {
            select.insert('<option value=' + el.id + '>' + el.text + '</option>');
            if(el.children) {
                checkChildren(el);
            }
        });
    }
    function checkChildren(el) {
        var child;
        var select = $('parent');
        for(var i = 0; i < el.children.count, child = el.children[i]; i++) {
            select.insert('<option value=' + child.id + '>' + child.text + '</option>');
            if(child.children) {
                checkChildren(child);
            }
        }
    }
    function getTree() {
        new Ajax.Request('<?php echo $this->getNewTreeUrl(); ?>',
                {
                    method:'POST',
                    onFailure:function () {
                        alert('Something went wrong...')
                    },
                    onComplete : function(transport) {
                        var response = eval('(' + transport.responseText + ')');
                        updateParentsList(response);
                    }
                })
    }
    function deleteElement() {
        new Ajax.Request('<?php echo $this->getDeleteUrl(); ?>',
                {
                    method:'POST',
                    parameters:{id:$('id').value},
                    onFailure:function () {
                        alert('Something went wrong...')
                    },
                    onComplete : function(transport) {
                        var response = eval('(' + transport.responseText + ')');

                        if (!response['parameters']) {
                            return false;
                        }
                        updateParentsList(response);
                        _renderNewTree(response);
                        addRoot();
                    }
                })
    }
    function saveElement() {
        if(!form.validate()) {
            return;
        }
        name = $('name').value;
        type = $('type').value;
        priority = $('priority').value;
        if (type == 1)
            value = $("catalog").value;
        else if (type == 2)
            value = $("page").value;
        else if (type == 3)
            value = $("address").value;
        new Ajax.Request('<?php echo $this->getSaveUrl(); ?>',
                {
                    method:'POST',
                    parameters:{name:name, id:$('id').value, parent:$('parent').value, type:type, value:value,
                        priority:priority },
                    onFailure:function () {
                        alert('Something went wrong...')
                    },
                    onComplete : function(transport) {
                        var response = eval('(' + transport.responseText + ')');
                        if (!response['parameters']) {
                            return false;
                        }
                        var oldParent = $('parent').value;
                        updateParentsList(response);
                        $('parent').value = oldParent;
                        _renderNewTree(response);
                    }
                })
        return false;
    }
    ;
</script>